version: '3'

services:
  python-discord-bot:
    container_name: python-discord-bot
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD=${DISCORD_GUILD}
      - CRYPTO_API=${CRYPTO_API}